"use strict";

// At the moment we don't support SVG
// Consider adding microdata and RDFa Lite
// If we end up supporting SVG, run svgo on the element first to normalise.
var htmlwhitelist = ["a",
"abbr",
"address",
"article",
"aside",
"audio",
"b",
"bdi",
"bdo",
"blockquote",
"br",
"caption",
"cite",
"code",
"colgroup",
"col",
"data",
"del",
"dfn",
"div",
"dl",
"dt",
"dd",
"em",
"figure",
"figcaption",
"footer",
"h1",
"h2",
"h3",
"h4",
"h5",
"h6",
"header",
"hr",
"i",
"img",
"ins",
"kbd",
"mark",
"math",
"nav",
"noscript",
"ol",
"p",
"pre",
"q",
"ruby",
"rt",
"rtc",
"rp",
"s",
"samp",
"section",
"small",
"source",
"span",
"strong",
"sub",
"sup",
"svg",
"table",
"tbody",
"tfoot",
"thead",
"th",
"tr",
"td",
"time",
"track",
"u",
"ul",
"video",
"var",
"wbr"];

var presentationalMathml = ["mi",
"mn",
"mo",
"mtext",
"mspace",
"ms",
"mrow",
"mfrac",
"msqrt",
"mroot",
"mstyle",
"merror",
"mpadded",
"mphantom",
"mfenced",
"menclose",
"msub",
"msup",
"msubsup",
"munder",
"mover",
"munderover",
"mmultiscripts",
"mtable",
"mlabeledtr",
"mtr",
"mtd",
"maligngroup",
"malignmark",
"mstack",
"mlongdiv",
"msgroup",
"msrow",
"mscarries",
"mscarry",
"msline"];

var tokenMathml = ["mglyph"];

var strictContentMathml = ["cn", "csymbol", "ci", "cs", "apply", "bind", "bvar", "share", "semantics", "cerror"];

var strictContentMathmlAttributes = {
  cn: ["xref", "href", "type"],
  ci: ["xref", "href", "type"],
  csymbol: ["xref", "href", "cd"],
  cs: ["xref", "href"],
  apply: ["xref", "href"],
  bind: ["xref", "href"],
  "bvar": ["xref", "href"],
  share: ["xref", "href", "src"],
  semantics: ["xref", "href"],
  cerror: ["xref", "href"]
};

var htmlAttributes = {
  a: [ "href", "name", "target", "download", "rel", "hreflang", "type"],
  img: [ "src", "alt", "width", "height" ],
  source: ["type", "src", "codecs"],
  "track": ["kind", "src", "srclang", "label", "default" ],
  "video": ["src", "crossorigin", "poster", "preload", "autoplay", "mediagroup", "loop", "muted", "controls", "width", "height"],
  "audio": ["src", "crossorigin", "preload", "autoplay", "mediagroup", "loop", "muted", "controls"],
  "table": ["border", "sortable"],
  "colgroup": ["span"],
  "col": ["span"],
  "td": ["colspan", "rowspan", "headers"],
  "th": ["colspan", "rowspan", "headers", "scope", "abbr", "sorted"],
  "blockquote": ["cite"],
  "ol": ["reversed", "start", "type"],
  "li": ["value"],
  "q": ["cite"],
  "data": ["value"],
  "time": ["datetime"],
  "ins": ["cite", "datetime"],
  "del": ["cite", "datetime"],
  "*": ["role", "class", "id", "dir", "hidden", "lang", "tabindex", "title", "translate"],
  math: ["display", "maxwidth", "overflow", "alttext", "cdgroup", "xref", "href"]
};

var presentationMathmlAttributes = {
  math: ["display", "maxwidth", "overflow", "alttext", "cdgroup", "xref", "href"],
  "mi": ["xref", "href", "mathcolor", "mathbackground", "mathvariant"],
  "mn": ["xref", "href", "mathcolor", "mathbackground"],
  "mo": ["xref", "href", "mathcolor", "mathbackground", "form", "fence",
    "separator", "lspace", "rspace", "stretchy", "symmetric", "maxsize",
    "minsize", "largeop", "movablelimits", "accent", "linebreak", "lineleading",
    "linebreakstyle", "linebreakmultchar", "indentalign", "indentshift", "indenttarget", "indentalignfirst", "indentshiftfirst", "indentalignlast", "indentshiftlast"],
  "mtext": ["xref", "href", "mathcolor", "mathbackground"],
  "mspace": ["xref", "href", "mathcolor", "mathbackground", "width", "height", "depth", "linebreak"],
  "ms": ["xref", "href", "mathcolor", "mathbackground", "lquote", "rquote"],
  "mrow": ["xref", "href", "mathcolor", "mathbackground"],
  "mfrac": ["xref", "href", "mathcolor", "mathbackground", "linethickness", "numalign", "denomalign", "bevelled"],
  "msqrt": ["xref", "href", "mathcolor", "mathbackground"],
  "mroot": ["xref", "href", "mathcolor", "mathbackground"],
  "mstyle": ["xref", "href", "mathcolor", "mathbackground", "scriptlevel", "displaystyle", "scriptsizemultiplier", "scriptminsize", "infixlinebreakstyle", "decimalpoint"],
  "merror": ["xref", "href", "mathcolor", "mathbackground"],
  "mpadded": ["xref", "href", "mathcolor", "mathbackground", "height", "width", "depth", "lspace", "voffset"],
  "mphantom": ["xref", "href", "mathcolor", "mathbackground"],
  "mfenced": ["xref", "href", "mathcolor", "mathbackground", "open", "closed", "separators"],
  "menclose": ["xref", "href", "mathcolor", "mathbackground", "notation"],
  "msub": ["xref", "href", "mathcolor", "mathbackground", "subscriptshift"],
  "msup": ["xref", "href", "mathcolor", "mathbackground", "superscriptshift"],
  "msubsup": ["xref", "href", "mathcolor", "mathbackground", "subscriptshift", "superscriptshift"],
  "munder": ["xref", "href", "mathcolor", "mathbackground", "accentunder", "align"],
  "mover": ["xref", "href", "mathcolor", "mathbackground", "accent", "align"],
  "munderover": ["xref", "href", "mathcolor", "mathbackground", "accent", "accentunder", "align"],
  "mmultiscripts": ["xref", "href", "mathcolor", "mathbackground"],
  "mtable": ["xref", "href", "mathcolor", "mathbackground", "align", "rowalign", "columnalign", "groupalign",
    "alignmentscope", "columnwidth", "width", "rowspacing", "columnspacing", "rowlines", "columnlines", "frame",
    "framespacing", "equalrows", "equalcolumns", "displaystyle", "side", "minlabelspacing"],
  "mlabeledtr": ["xref", "href", "mathcolor", "mathbackground"],
  "mtr": ["xref", "href", "mathcolor", "mathbackground", "rowalign", "columnalign", "groupalign"],
  "mtd": ["xref", "href", "mathcolor", "mathbackground", "rowspan", "columnspan", "rowalign", "columnalign", "groupalign"],
  "maligngroup": ["xref", "href", "mathcolor", "mathbackground", "groupalign"],
  "malignmark": ["xref", "href", "mathcolor", "mathbackground", "edge"],
  "mstack": ["xref", "href", "mathcolor", "mathbackground", "align", "stackalign", "charalign", "charspacing"],
  "mlongdiv": ["xref", "href", "mathcolor", "mathbackground", "longdivstyle"],
  "msgroup": ["xref", "href", "mathcolor", "mathbackground", "position", "shift"],
  "msrow": ["xref", "href", "mathcolor", "mathbackground", "position"],
  "mscarries": ["xref", "href", "mathcolor", "mathbackground", "position", "location", "crossout", "scriptsizemultiplier"],
  "mscarry": ["xref", "href", "mathcolor", "mathbackground", "location", "crossout"],
  "msline": ["xref", "href", "mathcolor", "mathbackground", "position", "length", "leftoverhang", "rightoverhang", "mslinethickness"],
  mglyph: ["src", "width", "height", "valign", "alt", "mathvariant", "mathsize"]
};

module.exports = {
  allowedTags: htmlwhitelist.concat(presentationalMathml, tokenMathml, strictContentMathml),
  allowedAttributes: Object.assign({}, htmlAttributes, strictContentMathmlAttributes, presentationMathmlAttributes)
};
